# Distância entre coordenadas geográficas

O resultado é em km desde que o raio da terra foi expresso em km ( R = 6373.0). Se você preferir o resultado em milhas, por exemplo, pode expressar R em milhas ('R = 3.958,8') 

In [1]:
import requests
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
# Para aparecer todas as linhas e colunas do dataset

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [6]:
df = pd.read_csv('/content/drive/MyDrive/Projetos_ion/ION_Smart_Locator/datasets/CNPJ_metadados/bairro_jardim_geolocalizado.csv')
df.head()

cnpj identificador_matriz_filial          nome_fantasia  \
0  37.392.382/0001-56                      MATRIZ                    NaN   
1  40.035.426/0001-03                      MATRIZ          GARAGE'S FOOD   
2  41.106.369/0001-60                      MATRIZ   PIZZARIA DA LINDAURA   
3  42.665.147/0001-40                      MATRIZ  EBENEZER A&V PINTURAS   
4  44.080.036/0001-06                      MATRIZ            ACAI DRINKS   

   pais  data_inicio_atividade  \
0   NaN               20200612   
1   NaN               20201207   
2   NaN               20210305   
3   NaN               20210711   
4   NaN               20211030   

                               cnae_fiscal_principal cnae_fiscal_secundaria  \
0                         Serviços de entrega rápida                    NaN   
1                           Restaurantes e similares                5611203   
2  Serviços de alimentação para eventos e recepçõ...                    NaN   
3          Serviços de pintura de edifícios em geral                4741500   
4  Comércio varejista de produtos alimentícios em...                    NaN   

  tipo_logradouro   logradouro numero complemento  \
0         AVENIDA   OURO VERDE    300     APT 202   
1             RUA  PIRATININGA     11         NaN   
2             RUA     DO CAMPO     11      CONJ 2   
3             RUA      CURVELO    315      CASA 2   
4         AVENIDA   OURO VERDE    238        CASA   

                         bairro       cep  uf           municipio  ddd1  \
0  JARDIM DE ALA (JUSTINOPOLIS)  33943700  MG  RIBEIRAO DAS NEVES  31.0   
1  JARDIM DE ALA (JUSTINOPOLIS)  33943630  MG  RIBEIRAO DAS NEVES  31.0   
2  JARDIM DE ALA (JUSTINOPOLIS)  33943233  MG  RIBEIRAO DAS NEVES  31.0   
3  JARDIM DE ALA (JUSTINOPOLIS)  33943770  MG  RIBEIRAO DAS NEVES  31.0   
4  JARDIM DE ALA (JUSTINOPOLIS)  33943700  MG  RIBEIRAO DAS NEVES  31.0   

    telefone1  ddd2  telefone2                correio_eletronico  \
0  88618906.0   NaN        NaN                               NaN   
1  99412433.0   NaN        NaN             GARAGESFOOD@GMAIL.COM   
2  85800232.0   NaN        NaN              LINDADARK9@GMAIL.COM   
3  87538949.0   NaN        NaN  AMAURIAURELINOAURELINO@GMAIL.COM   
4  75099824.0   NaN        NaN               FA8361272@GMAIL.COM   

                                            endereco  \
0  avenida ouro verde, ribeirao das neves, mg, br...   
1    rua piratininga, ribeirao das neves, mg, brasil   
2       rua do campo, ribeirao das neves, mg, brasil   
3        rua curvelo, ribeirao das neves, mg, brasil   
4  avenida ouro verde, ribeirao das neves, mg, br...   

                              endereco_geolocalizado   latitude  longitude  \
0  Avenida Ouro Verde, Vila Papine, Justinópolis,... -19.799550 -44.017191   
1  Rua Piratininga, Jardim de Alá, Justinópolis, ... -19.806701 -44.021607   
2  Rua do Campo, Eliane, Justinópolis, Ribeirão d... -19.814770 -44.020641   
3  Rua Curvelo, Vila Papine, Justinópolis, Ribeir... -19.803343 -44.020771   
4  Avenida Ouro Verde, Vila Papine, Justinópolis,... -19.799550 -44.017191   

                          geocoder  
0    (-19.79955, -44.0171908, 0.0)  
1  (-19.8067008, -44.0216066, 0.0)  
2  (-19.8147701, -44.0206408, 0.0)  
3  (-19.8033429, -44.0207707, 0.0)  
4    (-19.79955, -44.0171908, 0.0)

In [7]:
df.shape

(201, 25)

In [8]:
df = df.dropna(subset=['latitude', 'longitude'])
df.shape

(195, 25)

In [10]:
df.loc[:0]

cnpj identificador_matriz_filial nome_fantasia  pais  \
0  37.392.382/0001-56                      MATRIZ           NaN   NaN   

   data_inicio_atividade       cnae_fiscal_principal cnae_fiscal_secundaria  \
0               20200612  Serviços de entrega rápida                    NaN   

  tipo_logradouro  logradouro numero complemento  \
0         AVENIDA  OURO VERDE    300     APT 202   

                         bairro       cep  uf           municipio  ddd1  \
0  JARDIM DE ALA (JUSTINOPOLIS)  33943700  MG  RIBEIRAO DAS NEVES  31.0   

    telefone1  ddd2  telefone2 correio_eletronico  \
0  88618906.0   NaN        NaN                NaN   

                                            endereco  \
0  avenida ouro verde, ribeirao das neves, mg, br...   

                              endereco_geolocalizado  latitude  longitude  \
0  Avenida Ouro Verde, Vila Papine, Justinópolis,... -19.79955 -44.017191   

                        geocoder  
0  (-19.79955, -44.0171908, 0.0)

In [7]:
latitude = list(df.latitude)
longitude = list(df.longitude)

## Distance matrix entre coordenadas geográficas

In [23]:
import pandas as pd

import numpy as np
from math import sin, cos, sqrt, atan2, radians

from scipy.spatial.distance import pdist, squareform

In [9]:
lat_long = pd.DataFrame({'LATITUDE': latitude, 'LONGITUDE': longitude})

In [11]:
lat_long.head()

LATITUDE  LONGITUDE
0 -19.799550 -44.017191
1 -19.806701 -44.021607
2 -19.814770 -44.020641
3 -19.803343 -44.020771
4 -19.799550 -44.017191

Referencia da coordenada 1 pois essa será o ponto em que o vendedor está, por exemplo. Será a primeira linha do dataframe.

In [24]:
coord1 = eval(df.geocoder.loc[:0][0])

In [25]:
def dist(coord1, coord2):
    """Function to compute the distance between two points x, y"""
    result = pd.DataFrame()

    lat1 = radians(coord1[0])
    lon1 = radians(coord1[1])
    lat2 = radians(coord2[0])
    lon2 = radians(coord2[1])

    R = 6373.0

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c

    return round(distance, 4)

In [27]:
df['distancia'] = df.geocoder.apply(lambda x: dist(coord1,eval(x)))
df.head()

cnpj identificador_matriz_filial          nome_fantasia  \
0  37.392.382/0001-56                      MATRIZ                    NaN   
1  40.035.426/0001-03                      MATRIZ          GARAGE'S FOOD   
2  41.106.369/0001-60                      MATRIZ   PIZZARIA DA LINDAURA   
3  42.665.147/0001-40                      MATRIZ  EBENEZER A&V PINTURAS   
4  44.080.036/0001-06                      MATRIZ            ACAI DRINKS   

   pais  data_inicio_atividade  \
0   NaN               20200612   
1   NaN               20201207   
2   NaN               20210305   
3   NaN               20210711   
4   NaN               20211030   

                               cnae_fiscal_principal cnae_fiscal_secundaria  \
0                         Serviços de entrega rápida                    NaN   
1                           Restaurantes e similares                5611203   
2  Serviços de alimentação para eventos e recepçõ...                    NaN   
3          Serviços de pintura de edifícios em geral                4741500   
4  Comércio varejista de produtos alimentícios em...                    NaN   

  tipo_logradouro   logradouro numero complemento  \
0         AVENIDA   OURO VERDE    300     APT 202   
1             RUA  PIRATININGA     11         NaN   
2             RUA     DO CAMPO     11      CONJ 2   
3             RUA      CURVELO    315      CASA 2   
4         AVENIDA   OURO VERDE    238        CASA   

                         bairro       cep  uf           municipio  ddd1  \
0  JARDIM DE ALA (JUSTINOPOLIS)  33943700  MG  RIBEIRAO DAS NEVES  31.0   
1  JARDIM DE ALA (JUSTINOPOLIS)  33943630  MG  RIBEIRAO DAS NEVES  31.0   
2  JARDIM DE ALA (JUSTINOPOLIS)  33943233  MG  RIBEIRAO DAS NEVES  31.0   
3  JARDIM DE ALA (JUSTINOPOLIS)  33943770  MG  RIBEIRAO DAS NEVES  31.0   
4  JARDIM DE ALA (JUSTINOPOLIS)  33943700  MG  RIBEIRAO DAS NEVES  31.0   

    telefone1  ddd2  telefone2                correio_eletronico  \
0  88618906.0   NaN        NaN                               NaN   
1  99412433.0   NaN        NaN             GARAGESFOOD@GMAIL.COM   
2  85800232.0   NaN        NaN              LINDADARK9@GMAIL.COM   
3  87538949.0   NaN        NaN  AMAURIAURELINOAURELINO@GMAIL.COM   
4  75099824.0   NaN        NaN               FA8361272@GMAIL.COM   

                                            endereco  \
0  avenida ouro verde, ribeirao das neves, mg, br...   
1    rua piratininga, ribeirao das neves, mg, brasil   
2       rua do campo, ribeirao das neves, mg, brasil   
3        rua curvelo, ribeirao das neves, mg, brasil   
4  avenida ouro verde, ribeirao das neves, mg, br...   

                              endereco_geolocalizado   latitude  longitude  \
0  Avenida Ouro Verde, Vila Papine, Justinópolis,... -19.799550 -44.017191   
1  Rua Piratininga, Jardim de Alá, Justinópolis, ... -19.806701 -44.021607   
2  Rua do Campo, Eliane, Justinópolis, Ribeirão d... -19.814770 -44.020641   
3  Rua Curvelo, Vila Papine, Justinópolis, Ribeir... -19.803343 -44.020771   
4  Avenida Ouro Verde, Vila Papine, Justinópolis,... -19.799550 -44.017191   

                          geocoder  distancia  
0    (-19.79955, -44.0171908, 0.0)     0.0000  
1  (-19.8067008, -44.0216066, 0.0)     0.9199  
2  (-19.8147701, -44.0206408, 0.0)     1.7310  
3  (-19.8033429, -44.0207707, 0.0)     0.5642  
4    (-19.79955, -44.0171908, 0.0)     0.0000

In [16]:
lat_long.values

array([[-19.79955  , -44.0171908],
       [-19.8067008, -44.0216066],
       [-19.8147701, -44.0206408],
       [-19.8033429, -44.0207707],
       [-19.79955  , -44.0171908],
       [-19.7586995, -44.164044 ],
       [-19.8069192, -44.0209731],
       [-19.8065512, -44.0173894],
       [-19.8069192, -44.0209731],
       [-19.8069192, -44.0209731],
       [-19.8043261, -44.0208064],
       [-19.8069192, -44.0209731],
       [-19.8069192, -44.0209731],
       [-19.8043261, -44.0208064],
       [-19.8134407, -44.0201995],
       [-19.8069192, -44.0209731],
       [-19.8065512, -44.0173894],
       [-19.8065512, -44.0173894],
       [-19.8043261, -44.0208064],
       [-19.8134407, -44.0201995],
       [-19.8134407, -44.0201995],
       [-19.8134407, -44.0201995],
       [-19.79955  , -44.0171908],
       [-19.8043261, -44.0208064],
       [-19.8069192, -44.0209731],
       [-19.7586995, -44.164044 ],
       [-19.8069192, -44.0209731],
       [-19.8043261, -44.0208064],
       [-19.8134407,

In [15]:
distances = pdist(lat_long.values, metric=dist)
distances

array([0.9199, 1.731 , 0.5642, ..., 0.4471, 0.5642, 0.9982])

In [ ]:
for distance in distances:
  if distance < 1:
    points = [f'point_{i}' for i in range(1, len(lat_long) + 1)]
    result = pd.DataFrame(squareform(distances), columns=points, index=points)

result

point_1  point_2  point_3  point_4  point_5  point_6  point_7  \
point_1     0.0000   0.9199   1.7310   0.5642   0.0000  16.0283   0.9102   
point_2     0.9199   0.0000   0.9032   0.3836   0.9199  15.8355   0.0706   
point_3     1.7310   0.9032   0.0000   1.2711   1.7310  16.2532   0.8739   
point_4     0.5642   0.3836   1.2711   0.0000   0.5642  15.7967   0.3984   
point_5     0.0000   0.9199   1.7310   0.5642   0.0000  16.0283   0.9102   
point_6    16.0283  15.8355  16.2532  15.7967  16.0283   0.0000  15.9061   
point_7     0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_8     0.7790   0.4416   0.9755   0.5026   0.7790  16.2463   0.3773   
point_9     0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_10    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_11    0.6522   0.2771   1.1618   0.1094   0.6522  15.8278   0.2890   
point_12    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_13    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_14    0.6522   0.2771   1.1618   0.1094   0.6522  15.8278   0.2890   
point_15    1.5768   0.7640   0.1549   1.1248   1.5768  16.2399   0.7299   
point_16    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_17    0.7790   0.4416   0.9755   0.5026   0.7790  16.2463   0.3773   
point_18    0.7790   0.4416   0.9755   0.5026   0.7790  16.2463   0.3773   
point_19    0.6522   0.2771   1.1618   0.1094   0.6522  15.8278   0.2890   
point_20    1.5768   0.7640   0.1549   1.1248   1.5768  16.2399   0.7299   
point_21    1.5768   0.7640   0.1549   1.1248   1.5768  16.2399   0.7299   
point_22    1.5768   0.7640   0.1549   1.1248   1.5768  16.2399   0.7299   
point_23    0.0000   0.9199   1.7310   0.5642   0.0000  16.0283   0.9102   
point_24    0.6522   0.2771   1.1618   0.1094   0.6522  15.8278   0.2890   
point_25    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_26   16.0283  15.8355  16.2532  15.7967  16.0283   0.0000  15.9061   
point_27    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_28    0.6522   0.2771   1.1618   0.1094   0.6522  15.8278   0.2890   
point_29    1.5768   0.7640   0.1549   1.1248   1.5768  16.2399   0.7299   
point_30    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_31    0.7790   0.4416   0.9755   0.5026   0.7790  16.2463   0.3773   
point_32    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_33    0.7790   0.4416   0.9755   0.5026   0.7790  16.2463   0.3773   
point_34    0.0000   0.9199   1.7310   0.5642   0.0000  16.0283   0.9102   
point_35    1.0876   0.3305   0.6448   0.6448   1.0876  16.1154   0.2732   
point_36    0.9199   0.0000   0.9032   0.3836   0.9199  15.8355   0.0706   
point_37   16.0283  15.8355  16.2532  15.7967  16.0283   0.0000  15.9061   
point_38    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_39    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_40    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_41    0.5642   0.3836   1.2711   0.0000   0.5642  15.7967   0.3984   
point_42    1.0417   1.3742   2.2640   1.0698   1.0417  15.0127   1.4199   
point_43    0.0000   0.9199   1.7310   0.5642   0.0000  16.0283   0.9102   
point_44    0.0000   0.9199   1.7310   0.5642   0.0000  16.0283   0.9102   
point_45    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_46    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_47    0.0000   0.9199   1.7310   0.5642   0.0000  16.0283   0.9102   
point_48    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_49    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_50   16.0283  15.8355  16.2532  15.7967  16.0283   0.0000  15.9061   
point_51    0.9102   0.0706   0.8739   0.3984   0.9102  15.9061   0.0000   
point_52       NaN      NaN      NaN      NaN      NaN     

### Outra solução é:

O triângulo inferior da matriz de distância está vazio, pois a matriz é simétrica ( dist[i1,i2]==dist[i2,i1])

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from math import sin, cos, sqrt, atan2, radians

lat_long = pd.DataFrame({'LATITUDE':latitude, 'LONGITUDE': longitude})
lat_long

test = lat_long.iloc[2:,:]

def distance(city1, city2):
    lat1 = radians(city1['LATITUDE'])
    lon1 = radians(city1['LONGITUDE'])
    lat2 = radians(city2['LATITUDE'])
    lon2 = radians(city2['LONGITUDE'])

    R = 6373.0

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c

    return distance

dist = np.zeros([lat_long.shape[0],lat_long.shape[0]])
for i1, city1 in lat_long.iterrows():
    for i2, city2 in lat_long.iloc[i1+1:,:].iterrows():
        dist[i1,i2] = distance(city1, city2)

print(dist)

[[0.         0.91988577 1.73099947 ... 0.56422207 0.99820814 0.        ]
 [0.         0.         0.90321934 ... 0.383606   0.09518323 0.91988577]
 [0.         0.         0.         ... 1.27111824 0.87988257 1.73099947]
 ...
 [0.         0.         0.         ... 0.         0.44710448 0.56422207]
 [0.         0.         0.         ... 0.         0.         0.99820814]
 [0.         0.         0.         ... 0.         0.         0.        ]]
